---
title: "Understand the drivers of cyanobacteria blooms in Missisquoi and St. Albans Bays in 2017, 2018, and 2019 using high-frequency buoy sensor data"
author: "Wilton Burns & Mahalia Clark & Herman Njoroge Chege"
date: "11/1/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Research goal 

To better understand the drivers of cyanobacteria blooms in Missisquoi and St. Albans Bays in 2017, 2018, and 2019 using high-frequency buoy sensor data. And make beautiful documents in R markdown.

#### Personal research goals

-	Learn ecological forecasting model techniques and more about machine learning
-	Have help (and fun) intellectually interpreting the findings of the study and what data to include/how to prepare it for the model 
-	Use machine learning approaches to understand drivers of cyanobacteria blooms 
- Practice working with data in R and working with satellite imagery/data

#### Available Data

- High-frequency buoy monitoring data:
 Dissolved oxygen, pH, temperature, stratification, nutrient concentrations, salinity, cyanobacteria, etc.
- Long term monitoring:
Similar data over longer time periods but lower frequency
- Weather (solar radiation, wind speed & direction) and stream discharge
- Satellite imagery:
	Imagery of the bay is available and there are indices for mapping cyanobacteria & blooms. Satellite data: intensity of different spectral bands (visible, NIR) and indices combining bands for multiple time points.
- We found volunteer monitoring data with visual assessments of algae blooms for the two bays.

#### Project ideas/questions/sub-sections

(These will depend on our interests and rate of progress)

-	What environmental factors were driving the blooms in 2017, 2018, and 2019? 
-	Can we use the long-term monitoring data (since 1992 but less frequent time steps, no cyanobacteria levels) to forecast bloom dynamics in the bays? 
- Can we use high frequency data to forecast blooms?
-	How many days out can we forecast blooms (the best I’ve seen is a few days)? Does it change from year to year and bay to bay? 
-	We could compare PC and CHL data from buoy sensors to what the satellites pick up:
How well does the satellite spectral index for cyanobacteria correlate with buoy data on cyanobacteria concentrations? Is there a bloom threshold for the satellite index? Can we use this to determine a bloom threshold for the buoy sensor?
-	Combine high frequency buoy data (daily averages?) with available satellite imagery  for buoy locations. See if we can use all this data to predict/forecast buoy cyanobacteria concentrations and/or satellite cyanobacteria index.
-	See how well our model/forecast matches long term monitoring data: if we have our model trained with the buoy data, and we put in the long term data on water temp & concentrations, will it predict blooms when there were blooms? Or would it only work for short term forecasting with high frequency data? In that case, Wilton could still try to forecast blooms next summer.


